#  vim: set et fenc=utf-8 ff=unix sts=2 sw=2 ts=2 :
---
- name: cent_scripts | Get user home path
  shell: |
      export USERNAME=$(id -u -n) ;\
      export HOMEDIR=$(eval echo "~$(id -u -n)") ;\
      echo $HOMEDIR
  args:
    chdir: /home
    executable: /bin/bash
  register: cent_symlink__r_user_home

- set_fact:
    ansible_user_home: "{{ cent_symlink__r_user_home.stdout }}"

- set_fact:
    cent_scripts__home_bin_dir: "{{ ansible_user_home }}/.local/bin"

- name: cent_scripts | Create dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ cent_scripts__home_bin_dir }}"

- include_tasks: _install_scripts.yml
  loop: "{{ cent_scripts__tags }}"
  loop_control:
    loop_var: dir
